http_port 3128
acl localnet src 10.200.0.0/24
acl blocked dstdomain "/etc/squid/blocked_domains.txt"
acl blocked_extensions urlpath_regex -i \.(exe|bat|ps1|msi|scr)$
http_access deny blocked_extensions
http_access deny blocked
http_access allow localnet
http_access deny all
