http_port 3128
https_port 3129 intercept ssl-bump cert=/etc/squid/ssl_cert/myCA.pem
acl localnet src 10.200.0.0/24
acl blocked dstdomain "/etc/squid/blocked_domains.txt"
acl blocked_extensions urlpath_regex -i \.(exe|bat|ps1|msi|scr)$
acl step1 at_step SslBump1

ssl_bump peek step1
ssl_bump splice all

http_access deny blocked_extensions
http_access deny blocked
http_access allow localnet
http_access deny all

logformat detailed "%ts.%03tu %6tr %>a %Ss/%03>Hs %<st %rm %ru %[un %Sh/%<a %mt"
access_log /var/log/squid/access.log detailed
