[Interface]
Address = 10.200.0.2/24
PrivateKey = QPZt79jV2VVTd1qX+I0LFhl+pioNAlhP+ge+lm85+1E=

[Peer]
PublicKey = KAGDOazPtm2jehyeuJ3+Edm+cDpMrkSr5qfOGhvsp0Q=
Endpoint = 192.168.1.79:51820
AllowedIPs = 10.200.0.0/24
