[Interface]
# CLE PRIVEE DU SERVEUR
PrivateKey = 6A8uR1wETj6Csa8obrxZAgo6KEU43kAQj3rXL6cx2lg=
Address = 10.200.0.1/24
ListenPort = 51820

[Peer]
# CLE PUBLIC MACHINE LOCALE
PublicKey = vgrw+tPYz+1uq33pf1lkeccAiKPE0gbamPTS9VTIJj4=
AllowedIPs = 10.200.0.2/32
